### PR TITLE
Adjusted and tested the resistance temperature correction

### PR DESCRIPTION
**Pull request by miek770**
Hi Santiago,

In reference to #32.

I think this should be handled at the Devices.Branch level, not at the MultiCircuit level. We usually make this adjustement only for cables and lines, not transformers, and all conductors won't necessarily operate at the same temperature.

The formula you have provided in #32 is good. The one used by ETAP came from Southwire, who explained that it was developped from [yours](https://www.cirris.com/learning-center/general-testing/special-topics/177-temperature-coefficient-of-copper). Yours, however, can easily be found in other sources, including [Wikipedia](https://en.wikipedia.org/wiki/Electrical_resistivity_and_conductivity#Temperature_dependence) and the US' National Electrical Code (NFPA 70).

For the material thermal constant, I used those provided in footnote 2 of table 8 from the 2005 NEC for copper and aluminum at 75°C. As [Wikipedia](https://en.wikipedia.org/wiki/Electrical_resistivity_and_conductivity#Temperature_dependence) explains, those constant are not entirely linear so they should be taken closer to the expected operating temperature to improve accuracy, and the NEC is as good a reference as it gets (P.S.: Southwire had constants at 25°C).

I created an Enum for the ThermalConstant, and run Branch.apply_temperature() at its __init__() if the branch's Tb and Tc are different.

Open for discussion, as always. Thanks. If we wanted to overcomplicate things we could define constants at different reference temperatures, and use the one closes to Tb and Tc for our resistance correction, but that might be overkill.

### CODE REVIEW

**Comment by miek770** [comment]
Yes I used the Wikipedia formula, it's the same as found elsewhere (not the reconstructed one from Southwire & ETAP).

About the `R` parameter, I'd say it depends on how the information is presented in the GUI but I see your point. In the CLI it certainly doesn't happen without the user's explicit consent; you need to provide Tb and Tc and understand what they mean. We could simply change parameters:

- In the current PR I used `branch.R` as the current resistance (based on Tc) and `branch.Rref` as the reference temperature (based on Tb). In my case `Rref` is fixed and `R` is modified.

- We could replace `Rref` with `Rc`, keep `R` constant, calculate `Rc` based on `R`, `Tb` & `Tc`, and apply `Rc` at the `NumericalCircuit` level if the option is True (ex.: apply_temperature) and `Rc != R`. Would that be better?

For the data saving part, I assume you mean in the GridCal Excel format? We can certainly use something else if it's easier.

Thanks.

**Comment by SanPen** [comment]
Hi, 

I am against storing intermediate results in the database. Doing so is a bad practice that produces unmaintainable code on the long run. There are bad decisions in the code of GridCal under the light of today that seemed perfectly correct when I started.

One of those bad design decisions was to follow the Matpower scheme and have all lines, transformers, etc. modeled as a Branch. From my experience making software I can tell right now that having `R` and `Rref` is a very bad design decision since one is a linear combination of the other. Storing in a database values that you can calculate violates the first normal form of databases.

Another bad decision derived from having only one Branch model is that I have to write in the DB "Transformer" or "line", etc. depending on the branch model. To write in the DB Copper or Aluminum, would indubitably force the design to have a new table called `ThermalConstants` with the name and the value. Do we need that complexity? Not at the moment.

Eventually I'll correct those errors because their burden is becoming too high. I can see that that point is near since we want to have more device-specific models.

**So, what we can do now is:**

- We can have `Tb` and `Tc` as branch parameters (although we should think of better names)

- The thermal constants must be a number not an `enum`, otherwise we force users to change the source for new values.

- If you need The corrected resistance per branch we can implement a `get_corrected_resistance` function within the `Branch` object that can be used on demand but never in the compilation process in an element-wise fashion.  Having non-vector operations in the compilation process (like the correction of the temperature) makes the process very slow. That is what I had and I changed it. Now the compilation is 13 times faster as a result of that design decision. And that design decision allows enables new simulations that before were impractical.

- For larger calculations the correction of the resistance must remain the responsibility of `compute()` within the `NumericalCircuit` object.

**Comment by miek770** [comment]
Thank you for the thorough explaination; I'll modify my patch according to your comments and get back to you. I believe I understand your concerns.

Michel

**Comment by SanPen** [comment]
Thank you

**Comment by miek770** [comment]
Closing because of #53

**Pull request closed without merging**
