### PR TITLE
Other tests

### PR DESCRIPTION
**Pull request by miek770**
Hi,

Here are a few additional tests for GridCal, as well as a unit error correction in previous ones and some test renaming. They all run fine when `pytest` is called.

I'll add 1 or 2 other test for #32 when I get a chance (need ETAP to compare results).

Bye,

Michel

### CODE REVIEW

**Comment by miek770** [comment]
Was there something wrong with my PR? You seem to have redone the commits yourself instead of simply merging.

**Comment by SanPen** [comment]
It was more my incapacity to do a merge with conflicts, I need a good GIT editor that can handle those

**Comment by miek770** [comment]
Ok thanks, I'll try to avoid those in the future, I'm not sure why there were conflicts at all.

**Comment by SanPen** [comment]
You did nothing wrong, it was just that I am used to have an "accept theirs" vs "accept mine" option when merging with conflicts, and through github I was unable to find it.

GitHub suggested a series of commands to handle the merge but it was all a mess so I decided to commit the changes manually.

The conflict came because I added some spaces here and there.

**Comment by miek770** [comment]
Ok, so should I close the PR?

**Comment by SanPen** [comment]
If you see that I included everything I'd say yes

**Pull request closed without merging**
