### PR TITLE
Test HELM Research Package

### PR DESCRIPTION
**Pull request by Bengt**
Currently there are no tests covering the helm research package. Since this is the most interesting part for me, I would like to have it covered by tests and continuous integration. I noticed, that almost all of the helm implementation files actually have a main and can thus be executed on their own. So, I extracted that code into tests to be picked up by pytest. However, the main code does not work in most cases. It seems like the API has changed between the main code being written and the current GirdCal version. So I am creating this pull request for discussions of how to fix the main/test code.

### CODE REVIEW

**Comment by Bengt** [comment]
Hi @SanPen,

I am done with this for now. Travis fails, but again, I do not know where start debugging again. For debugging purposes, please refer to GitLab's CI:

<https://gitlab.com/GridCal/GridCal/pipelines>

There are already job in need of fixing, most recently:

<https://gitlab.com/GridCal/GridCal/-/jobs/275283904>

Regards,
Bengt

**Comment by SanPen** [comment]
I think it is alright to refactor these, but not to put them into production (tests)
There can be tests for sure, but not into the automated ones.

The main reason is that none of those helm algorithms "work" up to a reliable point. As you can see I abandoned them before refurbishing the calculation engine and that is why the interfaces are broken.

Maybe it is worth that we have a skype call or similar to talk about helm and how to proceed.

**Comment by SanPen** [comment]
Well I merged this one, huge mistake. I'm taking it back since there are plenty of broken references.

**Comment by Bengt** [comment]
Hi @SanPen,

thanks for the feedback and sorry I did not respond sooner; I can only work on this sporadically.

Since I used the stable HELM variant to sample some grids before, I would be interested in your thoughts about these research-quality algorithms. I would be open to skype with you about this pull request and effort to test more of the code base.

I have opened another pull request for my ongoing development.

Regards,
Bengt

**Comment by SanPen** [comment]
Hi, 

my skype is `santiago.penate.vera`, feel free to write and we can schedule a call to discuss these subjects.

Best regards,
Santiago

**Pull request merged**
