### PR TITLE
Extend Test Suite

### PR DESCRIPTION
**Pull request by Bengt**
While I am a fan of the recently-introduced continuous integration, it does not pick up all the tests. PyTest's test discovery requires all test files to be named `test_*` for example. This commit series makes that work for the most part. I could fix some tests that were dysfunctional, but others do not currently work. I deactivated these broken tests to make the continuous integration still succeed while now picking up most tests.

### CODE REVIEW

**Comment by Bengt** [comment]
There is an related issue: https://github.com/mu-editor/mu/issues/244

Running pytest takes up to 2 GB of memory (on my system), so that might cause Travisto fail.

**Comment by Bengt** [comment]
To demonstrate feasibility, I mirrored the repository to gitlab again an reconfigured the continuous integration there again:

https://gitlab.com/bengt/GridCal/pipelines/73318696

However, since Travis does not give a sensible error message, I have a hard time debugging that.

**Comment by SanPen** [comment]
Hi, 

The merging of this PR says that there rae no conflicts, but there are travis CI warnings about it failing... shall I merge this? is there any travis CI problem?

BR,
Santiago

**Comment by Bengt** [comment]
Please do not merge this until we have the continuous integration working again. I have too little information to make it work. Can you maybe restart the jobs in debug mode? I do not see that button:

https://docs.travis-ci.com/user/running-build-in-debug-mode/#restarting-a-job-in-debug-mode
https://travis-ci.org/SanPen/GridCal/jobs/564492491
https://travis-ci.org/SanPen/GridCal/jobs/564492492

**Comment by SanPen** [comment]
Unfortunately I do not see the debug mode either \:
I emailed them to get it activated...

**Comment by Bengt** [comment]
Hi, @SanPen!

Did you hear back from Travis, yet? It has been a week, so if not I would assume that they won't fix the build any time soon. In that case I would like to proceed without them, in order to not run into issues with the code base changing and rendering my test work worthless. One way to do that would be to use GitLab's CI from now on. That seems straightforward to me. One other way would be to deactivate the tests, that make Travis fail. However, I cannot say how much of the tests this would affect. How do you feel about this?

Regards,
Bengt

**Comment by SanPen** [comment]
They replied the following, which I find rather hacky...



Thanks for writing in!

I have just activated the debug feature for your SanPen/GridCal repository. Hope this helps!

The reason this is not enabled by default for public repositories is that anyone who happens to stumble across a log containing the SSH access can make a connection to the VM and potentially read out the secret environment variables.

Now you can start restarting your builds in Debug mode with an API request. To trigger a debug job:

Get your API token from your profile page at [https://travis-ci.org/profile](https://travis-ci.org/profile)

Send a POST request to /job/:job_id/debug replacing the TOKEN and JOB_ID values below:

```
#! /usr/bin/env bash
  curl -s -X POST \    
   -H "Content-Type: application/json" \    
   -H "Accept: application/json" \    
   -H "Travis-API-Version: 3" \    
   -H "Authorization: token <TOKEN>" \    
   -d '{ "quiet": true }' \    
   https://api.travis-ci.org/job/<JOB_ID>/debug  
```
The Job ID is displayed in the build log after expanding "Build system information".

Head back to the web UI and in the log of your job. There you should see the following lines to connect to the VM:
Setting up debug tools.
Preparing debug sessions.
Use the following SSH command to access the interactive debugging environment:
ssh ukjiuCEkxBBnRAe32Y8xCH0zj@ny2.tmate.io
Connect from your computer using SSH into the interactive session, and once you're done, just type exit and your build will terminate.
Once in the SSH session, these bash functions will come in handy to run the different phases in your build: [https://docs.travis-ci.com/user/running-build-in-debug-mode/#Things-to-do-once-you-are-inside-the-debug-VM](https://docs.travis-ci.com/user/running-build-in-debug-mode/#Things-to-do-once-you-are-inside-the-debug-VM)

**Comment by Bengt** [comment]
That procedure looks like a fun afternoon. However, I am not inclined to invest that amount of time into another CI system, while GitLab runs fine. Pinging @miek770 and @eyllanesc here to take this one over, if they are like.

**Comment by miek770** [comment]
I'll try to look into it this week and report back!

**Comment by Bengt** [comment]
Awesome. Thanks for having a crack at this!

**Comment by Bengt** [comment]
Sorry for breaking the build with commit 42c61d67, it is now fixed in commit 3e9c6af. I will keep my feet still now.

**Comment by miek770** [comment]
I found the issue; Travis doesn't like matplotlib in `test_demo_5_node.py`, `test_voltage_collapse.py` and perhaps others. Commenting those lines solves everything. It's not a memory issue.

Sorry I have to go get my daughter, but I can edit the PR once later today or tomorrow if no one beats me to it. Here's an example (git diff for the 5 node demo):

```
travis@travis-job-1215586a-9e0f-4ea5-bbe5-edd9535e3562:~/build/miek770/GridCal/src/tests$ git diff test_demo_5_node.py
diff --git a/src/tests/test_demo_5_node.py b/src/tests/test_demo_5_node.py
index 570351a..bfee5df 100755
--- a/src/tests/test_demo_5_node.py
+++ b/src/tests/test_demo_5_node.py
@@ -14,7 +14,7 @@
 # along with GridCal.  If not, see <http://www.gnu.org/licenses/>.
 
 import numpy as np
-from matplotlib import pyplot as plt
+# from matplotlib import pyplot as plt
 
 from GridCal.Engine.Core.multi_circuit import MultiCircuit
 from GridCal.Engine.Devices.branch import Branch
@@ -63,8 +63,8 @@ def test_demo_5_node(root_path):
     grid.add_branch(Branch(bus2, bus5, 'line 2-5', r=0.04, x=0.09, b=0.02))
     grid.add_branch(Branch(bus3, bus4, 'line 3-4', r=0.06, x=0.13, b=0.03))
     grid.add_branch(Branch(bus4, bus5, 'line 4-5', r=0.04, x=0.09, b=0.02))
-    grid.plot_graph()
-    print('\n\n', grid.name)
+    # grid.plot_graph()
+    # print('\n\n', grid.name)
 
     options = PowerFlowOptions(SolverType.NR, verbose=False)
 
@@ -73,8 +73,9 @@ def test_demo_5_node(root_path):
 
     print_power_flow_results(power_flow=power_flow)
 
-    fname = root_path / 'data' / 'output' / 'test_demo_5_node.png'
-    plt.savefig(fname=fname)
+    # fname = root_path / 'data' / 'output' / 'test_demo_5_node.png'
+    # plt.savefig(fname=fname)
+    assert True
 
 
 if __name__ == '__main__':
```

**Comment by Bengt** [comment]
Thanks for the patch, @miek770! To avoid friction, I made the changes you suggested. Unfortunately, the builds still fail with error out:

    The command "pytest" exited with 134.

**Comment by miek770** [comment]
Hi @Bengt, you also need to fix `test_voltage_collapse.py` (it also uses matplotlib). See diff below.

Sorry I would've done it myself, but I think I don't think I can push to this PR.

BTW, I checked and we're using matplotlib's latest version, so there's something wrong either with travis or with matplotlib. Either way, this issue should be tracked by either project (or both).

Here's the diff on `test_voltage_collapse.py`:

```
diff --git a/src/tests/test_voltage_collapse.py b/src/tests/test_voltage_collapse.py
index 3f6be30..394a99a 100644
--- a/src/tests/test_voltage_collapse.py
+++ b/src/tests/test_voltage_collapse.py
@@ -1,6 +1,6 @@
 from GridCal.Engine.IO.file_handler import *
 from GridCal.Engine.Simulations.ContinuationPowerFlow.voltage_collapse_driver import *
-from matplotlib import pyplot as plt
+# from matplotlib import pyplot as plt
 
 from tests.conftest import ROOT_PATH
 
@@ -31,11 +31,11 @@ def test_voltage_collapse(root_path):
     vc = VoltageCollapse(circuit=main_circuit, options=vc_options,
                          inputs=vc_inputs)
     vc.run()
-    vc.results.plot()
+    # vc.results.plot()
 
     fname = root_path / 'data' / 'output' / 'test_demo_5_node.png'
     print(fname)
-    plt.savefig(fname=fname)
+    # plt.savefig(fname=fname)
 
 
 if __name__ == '__main__':
```

With this (and the 5 node demo) fixed, Travis ran successfully in the debug VM (pytest successful).

If that still doesn't work, I'll investigate further.

**Comment by SanPen** [comment]
Maybe the matplotlib issues can be resolved by specifying the backend prior to importing pyplot:

```
import matplotlib
matplotlib.use('Qt5Agg')
from matplotlib import pyplot as plt
```

I use this code at work to deal with the lack of TKinter and PyQt5

**Comment by miek770** [comment]
I'll try and report back.

**Comment by miek770** [comment]
It also crashes with the backend specification:

```
travis@travis-job-7aff0ffa-38dc-4342-9807-2634b3355ef9:~/build/miek770/GridCal/src/tests$ pytest test_voltage_collapse.py 
================================================================ test session starts =================================================================
platform linux -- Python 3.7.1, pytest-4.3.1, py-1.7.0, pluggy-0.8.0
rootdir: /home/travis/build/miek770/GridCal, inifile: pytest.ini
collected 1 item                                                                                                                                     

test_voltage_collapse.py Aborted (core dumped)
```

BTW, pytest's log (with --debug) isn't helpful in this case; it captures no error.

**Comment by SanPen** [comment]
Then to remove `matplotlib` from the tests is the way forward I guess.

**Comment by Bengt** [comment]
Hi @miek770,

you could technically fork my fork and create pull request against it, fixing the issues with travis. But I made changes you suggested anyway. I even found some more plot calls and this made the builds finally work!

Regards,
Bengt

**Comment by Bengt** [comment]
Codacy still complains about the system calls. However, that is the cleanest way to call the tutorials that I am aware of.

@SanPen, I could not get `test_define_grid_from_scratch_with_profiles` to work and thus renamed it to `_test_define_grid_from_scratch_with_profiles`, hence excluding it from the test suite. Could you maybe have a look at it? Perhaps GridCal's API changed or something:

```
src/tests/test_tutorials.py:None (src/tests/test_tutorials.py)
test_tutorials.py:5: in <module>
    from GridCal.Tutorials import defining_a_grid_from_scratch_with_profiles
../GridCal/Tutorials/defining_a_grid_from_scratch_with_profiles.py:160: in <module>
    pf.run()
../GridCal/Engine/Simulations/PowerFlow/power_flow_driver.py:1668: in run
    results = self.pf.run()
../GridCal/Engine/Simulations/PowerFlow/power_flow_driver.py:1531: in run
    numerical_circuit = self.grid.compile()
../GridCal/Engine/Core/multi_circuit.py:692: in compile
    circuit.generator_power_profile[:, i_gen] = elm.P_prof
E   ValueError: could not broadcast input array from shape (25,1) into shape (25)
```

**Comment by miek770** [comment]
I would suggest merging this PR and opening a separate issue for Codacy. AFAIK, your PR didn't create the system calls that bug Codacy.

Likewise for the test that fails.

**Comment by Bengt** [comment]
I did actually introduce the system calls causing Codacy to complain by introducing a test for the tutorials. So this code quality regression should be fixed before merging this pull request. The relevant commit is:

https://github.com/SanPen/GridCal/pull/106/commits/42c61d673851a135cd86e410a3ede24abcb6b54e#diff-ef5b4beda8efbed44214111ff47ac3f9

**Comment by SanPen** [comment]
I think the easiest solution is to put the code of the tutorials into a function, and then call that function from the tests. I can merge and do that if you think we can merge this.

**Comment by Bengt** [comment]
@SanPen if you are okay with main functions in the tutorials, so am I. I followed your suggestion in the latest commit.

**Comment by Bengt** [comment]
So, yeah. Now I am happy with everything. Any more objections to merging this?

**Comment by Bengt** [comment]
Thanks for merging this! I am happy to have been able to contribute!

**Pull request merged**
